Db logic.
kysect/GithubActivityAnalyzer pull request #16
Opened 2021-04-03 10:14 UTC by ALEXXXANDRO

Я чувствую, что порой у меня возникают проблемы с неймингом, но не очень понимаю как правильно назвать то или иное.

В ActivityContext вхардкожена строка на путь к db, но ты вроде сказал, что пока это ок. Я потестил CRUD команды - кажется всё работает.

2021-04-03 11:24 UTC, FrediKats requested changes
В целом ок.

2021-04-03 11:24 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/DLL/Repositories/ActivityContext.cs
> +            => options.UseSqlite("Data Source=D:\\LABS\\Projects\\ActivityParser\\myDB.db");
Вхардкодить то конечно ладно, но хоть бы путь относительный)

2021-04-03 11:24 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/DLL/Entities/UserCash.cs
> +    public class UserCash
Кажется, ты не в нейминг не смог, а в английский

2021-04-03 11:24 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/DLL/Repositories/UserCashRepository .cs
> +        public UserCash GetByUsername(string username)
Лучше FindBy. Get обозначат то, что всегда не null вернет. А ты просто вызываешь Find и все.

2021-04-03 11:34 UTC, ALEXXXANDRO commented on Kysect.GithubActivityAnalyzer/DLL/Entities/UserCash.cs
> +    public class UserCash
Bruh b1

2021-04-03 11:34 UTC, ALEXXXANDRO commented
Сча в автобус сяду - поправлю

2021-04-05 08:38 UTC, FrediKats approved these changes

2021-04-05 08:39 UTC, FrediKats approved these changes

2021-04-05 08:39 UTC, merged