Add parallel download by list
kysect/GithubActivityAnalyzer pull request #23
Opened 2021-04-05 18:19 UTC by ALEXXXANDRO

Не уверен что это всё что нужно было сделать, но ничего другого в голову не приходит.

2021-04-05 20:58 UTC, FrediKats requested changes
Ну, это выглядит как параллельность. Но когда в группах выполняется в один поток. А именно там и будет происходить большинство запросов. Нужно заюзать параллельность везде, где мы явно вытаскивать пытаемся сразу пачку.

2021-04-07 13:05 UTC, ALEXXXANDRO commented
Вроде теперь всё. При первом вызове метода GetShortInfo() вылезла какая то ошибка, которую я случайно закрыл. Когда запустил снова - всё заработало. Не знаю что это было, но я решил на всякий случай сообщить об этом.

2021-04-07 17:22 UTC, FrediKats requested changes
Ну не, это совсем не то. Ты понадобавлял в куче мест многопоточку, это не очевидные плохо переиспользуемые методы. Не пытайся подогнать многопоточку под код, переделай лучше код так, чтобы там нормально многопоточка юзалась.
Должно быть ровно одно место - один метод в GithubActivityProvider, который принимает список и опциональный флаг на использование мнгопоточки. Все остальные места в коде должны через него работать.

2021-04-12 05:25 UTC, I-SER-I commented on Kysect.GithubActivityAnalyzer/Services/GithubActivityProvider.cs
> +                return result;
Поменять на нормальные LINQ

2021-04-12 12:03 UTC, FrediKats approved these changes

2021-04-12 12:03 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Services/GithubActivityProvider.cs
> +        public IEnumerable<Student> GetStudentListInfo(string[] usernames, bool isParallel)
Лучше лист вернуть чтобы сразу выполнение проходило, а не отложенно.

2021-04-12 12:04 UTC, FrediKats commented
Теперь во всех местах параллелинг? Он работает вместе с кешом?

2021-04-12 15:03 UTC, FrediKats approved these changes

2021-04-12 15:04 UTC, merged