feat(get stat from api)
kysect/GithubActivityAnalyzer pull request #24
Opened 2021-04-10 22:10 UTC by TomGnill

2021-04-11 05:51 UTC, FrediKats approved these changes

2021-04-11 05:51 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Client/Pages/GetStudyGroup.razor
> +        Usernames.Reverse();
А зачем реверсить?

2021-04-11 05:51 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Client/Pages/GetStudyGroup.razor
> +        gGroup = response.Content.ReadFromJsonAsync<Services.StudyGroup>().Result;
А ему ок, что ты .REusult вызываешь вместо вызова через await?

2021-04-11 08:51 UTC, TomGnill commented on Kysect.GithubActivityAnalyzer.WebDemo/Client/Pages/GetStudyGroup.razor
> +        Usernames.Reverse();
Короче в чем проблема, мне надо как-то передать номер группы в пост, я пробовал кортеж, но через него все в  . Null  превращается Почему-то, сделал так чтобы первый элемент был номером группы, поэтому он добавляется сюда и становится первым в списке

2021-04-11 08:51 UTC, TomGnill commented on Kysect.GithubActivityAnalyzer.WebDemo/Client/Pages/GetStudyGroup.razor
> +        gGroup = response.Content.ReadFromJsonAsync<Services.StudyGroup>().Result;
На мое удивление да

2021-04-11 12:23 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Client/Pages/GetStudyGroup.razor
> +        Usernames.Reverse();
Звучит как костыль Если тебе нужен номер - передавай его.

2021-04-12 05:30 UTC, FrediKats requested changes

2021-04-12 05:30 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Shared/ControllerGroupInfo.cs
> +   public class ControllerGroupInfo
А почему такое странное название?

2021-04-12 05:30 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Client/Pages/GetStudyGroup.razor
> +    private ControllerGroupInfo newGroupInfo = new ControllerGroupInfo();
Зачем хранить поле, если ты создаешь в методу GetStat и больше не юзаешь?

2021-04-12 05:30 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Client/Pages/GetStudyGroup.razor
> +        List<string> input = Usernames;
Зачем переменная эта?

2021-04-12 05:30 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Client/Pages/GetStudyGroup.razor
> +    private Services.StudyGroup gGroup = new Services.StudyGroup();
Нейминг

2021-04-12 05:30 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Client/Pages/GetStudyGroup.razor
> +    private int Contributions { get; set; } = 0;
Зачем это поле, если можно из gGroup доставать эту инфу?

2021-04-12 05:30 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Client/Pages/GetStudyGroup.razor
> +    private bool StatsIsVisible { get; set; } = false;
Почему бы не проверять по gGroup == null?

2021-04-12 05:30 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Client/Pages/GetStudyGroup.razor
> +        gGroup = response.Content.ReadFromJsonAsync<Services.StudyGroup>().Result;
Для эдинообразия я бы заменил на await и тут.

2021-04-12 05:30 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Client/Pages/TestPage.razor
> +        Info = JsonSerializer.Deserialize<ActivityInfo>(response);
Есть же метод, который сам десереализует

2021-04-12 05:30 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Client/Pages/TestPage.razor
> +        Contributions = Info.Total;
Зачем это поле? Оно же вычисляемое.

2021-04-12 06:57 UTC, TomGnill commented on Kysect.GithubActivityAnalyzer.WebDemo/Client/Pages/GetStudyGroup.razor
> +        List<string> input = Usernames;
а, это так смёрджилось почему-то, ты наверное и сам заметил что оно тут не нужно)

2021-04-12 06:58 UTC, TomGnill commented on Kysect.GithubActivityAnalyzer.WebDemo/Shared/ControllerGroupInfo.cs
> +   public class ControllerGroupInfo
У нас уже есть GroupInfo, меня смутило называть ещё один класс таким именем

2021-04-12 15:03 UTC, FrediKats approved these changes

2021-04-12 15:25 UTC, FrediKats approved these changes

2021-04-12 15:26 UTC, merged