Feat dashboard
kysect/GithubActivityAnalyzer pull request #49
Opened 2021-08-04 06:19 UTC by ALEXXXANDRO

Добавил дашборд, который подгружает статистику команды из базы данных, либо сообщает, что такой команды нет.

P.S. Я не знаю, насколько правильно было засовывать ссылки на скрипты в index.html, так что если это плохо - хотелось бы узнать как надо
![image](https://user-images.githubusercontent.com/61233191/128131278-e9d9a002-8175-4c81-8fae-e27866d19998.png)

2021-08-08 07:36 UTC, FrediKats requested changes

2021-08-08 07:36 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Server/Services/TeamService.cs
> +        Team ITeamService.GetTeam(Team team)
Перенос строки между методами.
Убери ITeamService.

2021-08-08 07:36 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Server/Services/TeamService.cs
> +            team.Usernames = _teamRepository.GetAllByTeam(team.TeamName).Select(p => p.Username).ToList();
Это что-то не очень правильное. Если этому методу на вход нужен только TeamName, то его и нужно передавать.

2021-08-08 07:36 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Server/Services/ITeamService.cs
> +        public Team GetTeam(Team teamName);
Убери public из интерфейса.

2021-08-08 07:36 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Server/Controllers/DBTeamController.cs
> +        [HttpPost("GetTeam")]
Кажется, тут можно будет заменить на Get если вместо Team передавать string.

2021-08-08 07:36 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Server/Controllers/DBTeamController.cs
> +        [HttpPost("GetTeam")]
А ещё посмотри в сторону IActionResult

2021-08-08 07:36 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Client/wwwroot/js/Chart.js
> +﻿function GenerateBarChart(teamInfo) {
Ты решил прям сразу на js писать?)

2021-08-08 07:36 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Client/Pages/UnitedStat.razor.cs
> +namespace Kysect.GithubActivityAnalyzer.WebDemo.Client.Pages
Отсутпы)

2021-08-08 07:36 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Client/Pages/UnitedStat.razor.cs
> +                Usernames = _usernames
У тебя должна на сервере хранится информация о том, кто есть в команде. И названия должно быть достаточно, чтобы получить активность.

2021-08-08 07:36 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Client/Pages/UnitedStat.razor.cs
> +        }
Наверное, это должно не локально добавлять, а отправлять на сервер команду AddStudent, чтобы он добавился в команду.

2021-08-08 07:36 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Client/Pages/UnitedStat.razor.cs
> +            var response = await Http.PostAsJsonAsync("Team", newTeamInfo);
Потыкай @MGSDS, он тебе расскажет как он в SeaInk планирует реализовывать Sdk проект и выносить такие запросы.

2021-08-08 07:36 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Client/Pages/Dashboards/TeamDashboard.razor.cs
> +            var team = await Http.PostAsJsonAsync("DBTeam/GetTeam", new Team(_teamName));
Урлы какие-то очень странные. Почему есть Team и DbTeam?)

2021-08-08 07:36 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Client/Pages/Dashboards/TeamDashboard.razor.cs
> +                _team = await teamResponse.Content.ReadFromJsonAsync<TeamResponse>();
Если я правильно понял, что тут одним запросом список получается юзеров, а вторым - их активность? Не лучше тогда ли сделать методы, чтобы по урлам было понтяно? Team/GetMembers Team/GetStats? (и во второй не передавать, наверное, список участников т.к. это на сервере должно и так хранится.)

2021-08-08 12:10 UTC, ALEXXXANDRO commented on Kysect.GithubActivityAnalyzer.WebDemo/Server/Services/TeamService.cs
> +            team.Usernames = _teamRepository.GetAllByTeam(team.TeamName).Select(p => p.Username).ToList();
Я не смог найти нашу переписку по этому поводу, но ты сам сказал что так можно сделать. 

Там проблема в том, что если сделать запрос к контроллеру, в который передается string, то он как то неадекватно себя ведёт и эта string просто пропадает и приходит то ли 0 то ли null => никто ничего сформировать по такому TeamName не может.  И мы тогда вроде пришли к тому, что можно передать Team с пустым полем usernames.

2021-08-08 12:18 UTC, ALEXXXANDRO commented on Kysect.GithubActivityAnalyzer.WebDemo/Client/Pages/UnitedStat.razor.cs
> +                Usernames = _usernames
Это немного не туда. На этой страничке ты в режиме реального времени формируешь команду. Т.е. ручками добавляешь в новую команду одного, второго, третьего, а потом смотришь стату того что сформировал.  

(Этот функционал уже был, просто я вынес его в partial class)
Наверно не стоило засовывать это в ПР по дашбордам, т.к. это не имеет к ним отношения.

2021-08-08 18:29 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Server/Services/TeamService.cs
> +            team.Usernames = _teamRepository.GetAllByTeam(team.TeamName).Select(p => p.Username).ToList();
Окей, заведи ишую на ресёрч проблемы, я потом посмотрю и поправлю. Это скорее временное решение)

2021-08-14 08:15 UTC, ALEXXXANDRO commented
Немного не понимаю откуда взялись новые конфликты. Если до этого были разные версии пакетов, то теперь я просто добавил ещё один...

И второе - что именно ты имел ввиду, когда говорил тыкнуть человека и посмотреть как он реализует такие запросы? 
Имелось ввиду, что там нужен GET а не POST или что?

2021-08-14 19:24 UTC, FrediKats commented
Чтобы пофиксить, проще всего вмёрджить мастер ветку в твою.
Нет, я не про то, что нужен гет или пост. Можешь пока забить, я ишую заведу, потом обсудим, это не приоритет задача.

2021-08-16 13:35 UTC, FrediKats requested changes

2021-08-16 14:23 UTC, ALEXXXANDRO commented on Kysect.GithubActivityAnalyzer.WebDemo/Server/Services/ITeamService.cs
> +        bool TryGetTeam(Team teamName, out Team team);
В доке майкрософта просто был такой пример, и я решил, что, наверно так принято

2021-08-16 14:35 UTC, ALEXXXANDRO commented on Kysect.GithubActivityAnalyzer.WebDemo/Server/Controllers/TeamInfoController.cs
> +    public class TeamInfoController : Controller
Просто у нас есть сущность TeamResponse, которая представляет собой агрегацию статистики и members, и из неё как раз и происходит процесс извлечения всякой информации.  У меня язык не повернулся назвать TeamResponseController, хотя мб я не прав. TeamController не очень подходит, т.к. есть DBTeamController который нужен для CRUD команд в базе

2021-08-16 16:11 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.WebDemo/Server/Controllers/TeamInfoController.cs
> +    public class TeamInfoController : Controller
Ладно, потом перепишем всё )

2021-08-16 16:11 UTC, FrediKats approved these changes
Будем допиливать потом.

2021-08-16 16:16 UTC, FrediKats commented
@ALEXXXANDRO посмотри, там сонар тебе написал, что стоит пофиксить async void. Можешь заодно почитать почему.

2021-08-17 14:56 UTC, ALEXXXANDRO commented on Kysect.GithubActivityAnalyzer.WebDemo/Server/Controllers/TeamInfoController.cs
> +        public TeamResponse GetTeamInfo(Shared.Team info)
не очень, потому что есть Aggregators.Team и Shared.Team

2021-08-17 14:59 UTC, ALEXXXANDRO commented
@FrediKats  можно тогда ещё по поводу этого уточнить? Где по идее они должны лежать?
![image](https://user-images.githubusercontent.com/61233191/129750169-48e6e896-8440-43bc-8894-f573dc211b06.png)

2021-08-17 16:08 UTC, FrediKats commented
В теории, их быть не должно...

2021-08-17 16:12 UTC, FrediKats commented
В идеале, было бы неплохо заюзать шарповую либу, а не на js писать. Я всё ещё не понял, почему ты решил писать на js) Я бы пока забил, а потом переделал.

2021-09-03 19:40 UTC, FrediKats approved these changes

2021-09-03 19:40 UTC, merged